'''
This document 'TextRankAnalysis.py' reads the ouptut CSV generated by the TextRank algorithm to analyze and visualize the results.
Note that this script analyzes TextRankOutputFinished.csv, as opposed to TextRankOutput.csv, which is generated by TextRank.py.

The difference in output names is to avoid accidentally overwriting the output generated by TextRank.py.

@author Nisanur Genc
@author Alex Wills
'''

import matplotlib.pyplot as plt
import os
import csv
import DatasetAnalysis as analyze



def main():

    # The output file to analyze
    output_file = 'TextRankOutputFinished.csv'

    rootdir = os.path.dirname(__file__)

    oneshot = True

    document_lengths = analyze.build_length_dict()

    # X and Y axis lists for scatterplot
    lengths = []
    scores = []

    with open( os.path.join(rootdir, output_file), mode='r', encoding='utf-8') as outfile:
        header = outfile.readline()
        reader = csv.reader(outfile)

        for entry in reader:
            doc_size = document_lengths[entry[0]]
            score = entry[-1]

            lengths.append(int(doc_size))
            scores.append(float(score))

    
    avg_score = sum(scores) / len(scores)
    print("Average Rouge-2 Score:", avg_score)
    min_score = min(scores)
    max_score = max(scores)
    print("Minimum Score:", min_score)
    print("Maximum Score:", max_score)

    plt.scatter(lengths, scores)
    plt.xlabel("Document Size (# Sentences)")
    plt.ylabel("Rouge-2 Score")
    plt.show()
        

if __name__ == "__main__":
    main()